### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by krues8dr** [clef/handbook#30]
It's awesome that you all have released this - but for other organizations to use it, you really will need to add a license. If the whole thing was created in-house or as a work-for-hire, you should be able to release it as [CC0](https://creativecommons.org/publicdomain/zero/1.0/) as we've done, which allows anyone to use and modify it however they like!

**Comment by jessepollak** [comment]
Thanks, on it!

**Comment by krues8dr** [comment]
MIT is a bit of a strange license to pick for a series of documents - but it's better than nothing!  Thanks!

**Comment by jessepollak** [comment]
Moving too fast — should have gone with CC0. Will change!

**Comment by krues8dr** [comment]
:+1:

**Comment by jessepollak** [comment]
Do you have a text version that y'all use? Link?

**Comment by krues8dr** [comment]
Ta da!   https://github.com/opengovfoundation/hr-manual/blob/master/LICENSE

**Comment by jessepollak** [comment]
Opened a PR here: https://github.com/clef/handbook/pull/34/files

Look good?

**Comment by krues8dr** [comment]
Really good!  One tweak - rename it to `LICENSE` instead of `LICENSE.md` and [Github's license API will pick it up automagically](https://developer.github.com/v3/licenses/)!
