### ISSUE TITLE
Use tags to preserve handbook history

### ISSUE THREAD

**Issue by metavida** [clef/handbook#71]
I was considering how your handbook might grow & change over time both as the number of employees at your company grows and as some of your employees gain tenure. It might be interesting to add tags to the repo to mark certain company milestones (e.g. "10-30 employees", "1 year in business"). This might let future startups more easily look back at versions of your policies that worked well for you when Clef was smaller/younger, and in the future might let you reflect on how your policies have changed as you became a larger company.

**Comment by brennenbyrne** [comment]
I'm rusty with Github -- @jessepollak how feasible is this / how would we do it?

**Comment by jessepollak** [comment]
Absolutely possible. We'll definitely tag before we start working on the post-seed version and there may be other milestones before then that we can also tag. Also adding a tag for initial launch right now, thanks!
