### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ivank** [clef/handbook#78]
Guys I'm very very excited that you're doing this, and would hope more and more companies adopt your ideas and implementation, with enough of these around and open to everyone for review and to learn from we could probably achieve sort of "creative commons" of company policies, with easy and well-understood best practises... Oh the possibilities.
Anyway your documents are great and very straight forward, but I think you're lacking more concrete examples - you could probably link to a some do's and don'ts (especially disputed ones) or maybe link to sources (if available) as to why the conclusions in the documents are the way they are, allowing for more scrutiny, oversight and reasoning to be done by everybody. 
I know you're probably know all the reasons and would like to keep this document as clean as possible providing only the distilled information, but it would be great for people outside of your community to glean more into your process that way, and I'm sure new (and possible future remote) employees would appreciate the extra sources.
And again thanks for your great contribution to society!

**Comment by nrrrdcore** [comment]
@ivank thank you for these thoughts! I agree and would love to see concrete research linked to, if possible.

🌟💫
